title: Doved Studio
description: Doved Studio livre des apps iOS/Android, SaaS, et jeux vidéo en 6 à 12 semaines avec forfait fixe incluant design, développement, QA, et 3 mois de support post-lancement.
url: ""
baseurl: ""
theme: jekyll-theme-cayman